#!/bin/sh
echo " who am i taking to ?"
read user_name
echo "Hello $user_name"
------------------------
echo "today is:" `date`
output :
today is : 30-11-2024
----------------------
$echo $HOME : prints the home working directory 
# $HOME is a global/environmental variable
------------------------------------------------
a = 1234
b = `expr $a + 1`
will perform arithemetic operation (ie 1234+1 = 1235)
# expr supports the following :
# +, - ,* , / , % , < , <= , == , != , >= , > , & , | , parentheses
-----------------------------------------------------
b = abc def is invalid
b = 'abc def' is valid
-----------------------------------------------------
if date | grep "Fri"
then
     echo " It is Friday"
fi
------------------------------------------------------
if [ "$1" == "Monday" ]
then
    echo "Monday"
elif [ "$1" == "Tuesday" ]
then
    echo "Tuesday"
else
     echo "its is neither monday or tuesday"
fi
------------------------------------------------------
#functions:
sum(){
  x='expr $1 + $2`
  echo $x
}
echo "the sum of 5 and 3 is `sum 5 3` "
---------------------------------------------------------
# write algorithm for 'stash.c'
while(ringbuffer_is_full){
interruptible_sleep_on(&wq);
if(signal_pending(current))
return -EINTR;}
insert byte from user-space intoo ringbuffer;
wake_up_interruptible(&wq);
return 1;
------------------------------------------------------------
while(ringbuffer_is_empty){
interruptible_sleep_on(&wq);
if(signal_pending(current))
return -EINTR;
}
remove byte from ringbuffer and store to user space;
wake_up_interruptible(&wq);
return 1;
---------------------------------------------------------------



